#!/bin/bash

# SMCLab.net Demo Stack Deployment Script
set -e

echo "🚀 Deploying SMCLab.net Demo Stack..."

# Check if Docker is running
if ! docker info >/dev/null 2>&1; then
    echo "❌ Docker is not running. Please start Docker and try again."
    exit 1
fi

# Check if Docker Compose is available
if ! command -v docker-compose >/dev/null 2>&1; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose and try again."
    exit 1
fi

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p letsencrypt
chmod 600 letsencrypt

# Set correct permissions for Let's Encrypt directory
if [ ! -f letsencrypt/acme.json ]; then
    touch letsencrypt/acme.json
    chmod 600 letsencrypt/acme.json
fi

# Pull latest images
echo "📦 Pulling latest Docker images..."
docker-compose pull

# Stop any existing containers
echo "🛑 Stopping existing containers..."
docker-compose down --remove-orphans

# Create external network if it doesn't exist
echo "🌐 Setting up networks..."
docker network ls | grep -q web || docker network create web

# Start the stack
echo "🔧 Starting the Docker stack..."
docker-compose up -d

# Wait for services to be ready
echo "⏳ Waiting for services to start..."
sleep 10

# Check service status
echo "📊 Checking service status..."
docker-compose ps

echo ""
echo "✅ Deployment complete!"
echo ""
echo "🌐 Your services are available at:"
echo "   • https://demo1.smclab.net"
echo "   • https://demo2.smclab.net"
echo "   • https://demo3.smclab.net"
echo "   • https://traefik.smclab.net (Traefik Dashboard)"
echo ""
echo "📋 Database Info:"
echo "   • Host: localhost:5432"
echo "   • Database: demo_db"
echo "   • User: demo_user"
echo "   • Password: demo_password"
echo ""
echo "🔧 Useful commands:"
echo "   • View logs: docker-compose logs -f"
echo "   • Stop stack: docker-compose down"
echo "   • Restart: docker-compose restart"
echo ""
echo "⚠️  Note: SSL certificates will be automatically generated by Let's Encrypt."
echo "   Make sure your domains point to this server's IP address."