version: '3.8'

volumes:
  certs:
  vhost:
  html:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  nginx-proxy-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=da@madbox.co.uk
    restart: unless-stopped
  demo1:
    image: nginx:alpine
    container_name: demo1_smclab
    environment:
      - VIRTUAL_HOST=demo1.smclab.net
      - LETSENCRYPT_HOST=demo1.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo1:/usr/share/nginx/html
      - ./demo1/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  demo2:
    image: nginx:alpine
    container_name: demo2_smclab
    environment:
      - VIRTUAL_HOST=demo2.smclab.net
      - LETSENCRYPT_HOST=demo2.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo2:/usr/share/nginx/html
      - ./demo2/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  demo3:
    image: nginx:alpine
    container_name: demo3_smclab
    environment:
      - VIRTUAL_HOST=demo3.smclab.net
      - LETSENCRYPT_HOST=demo3.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo3:/usr/share/nginx/html
      - ./demo3/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped