version: '3.8'

services:
  demo1:
    image: nginx:alpine
    container_name: demo1_smclab
    ports:
      - "81:80"
    volumes:
      - ./demo1:/usr/share/nginx/html
      - ./demo1/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  demo2:
    image: nginx:alpine
    container_name: demo2_smclab
    ports:
      - "82:80"
    volumes:
      - ./demo2:/usr/share/nginx/html
      - ./demo2/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  demo3:
    image: nginx:alpine
    container_name: demo3_smclab
    ports:
      - "83:80"
    volumes:
      - ./demo3:/usr/share/nginx/html
      - ./demo3/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped