version: '3.8'

volumes:
  certs:
  vhost:
  html:
  postgres_data:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  nginx-proxy-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=da@madbox.co.uk
    restart: unless-stopped
  demo1:
    image: webdevops/php-nginx:8.2-alpine
    container_name: demo1_smclab
    environment:
      - VIRTUAL_HOST=demo1.smclab.net
      - LETSENCRYPT_HOST=demo1.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo1:/app
      - ./demo1/conf/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    restart: unless-stopped
    depends_on:
      - postgres

  demo2:
    image: webdevops/php-nginx:8.2-alpine
    container_name: demo2_smclab
    environment:
      - VIRTUAL_HOST=demo2.smclab.net
      - LETSENCRYPT_HOST=demo2.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo2:/app
      - ./demo2/conf/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    restart: unless-stopped
    depends_on:
      - postgres

  demo3:
    image: webdevops/php-nginx:8.2-alpine
    container_name: demo3_smclab
    environment:
      - VIRTUAL_HOST=demo3.smclab.net
      - LETSENCRYPT_HOST=demo3.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo3:/app
      - ./demo3/conf/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    restart: unless-stopped
    depends_on:
      - postgres

  demo4:
    image: webdevops/php-nginx:8.2-alpine
    container_name: demo4_smclab
    environment:
      - VIRTUAL_HOST=demo4.smclab.net
      - LETSENCRYPT_HOST=demo4.smclab.net
      - LETSENCRYPT_EMAIL=da@madbox.co.uk
    volumes:
      - ./demo4:/app
      - ./demo4/conf/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_smclab
    environment:
      - POSTGRES_DB=smclab_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - "5432:5432"