version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  demo1:
    image: nginx:alpine
    container_name: demo1_smclab
    environment:
      - VIRTUAL_HOST=demo1.smclab.net
    volumes:
      - ./demo1:/usr/share/nginx/html
      - ./demo1/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  demo2:
    image: nginx:alpine
    container_name: demo2_smclab
    environment:
      - VIRTUAL_HOST=demo2.smclab.net
    volumes:
      - ./demo2:/usr/share/nginx/html
      - ./demo2/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  demo3:
    image: nginx:alpine
    container_name: demo3_smclab
    environment:
      - VIRTUAL_HOST=demo3.smclab.net
    volumes:
      - ./demo3:/usr/share/nginx/html
      - ./demo3/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped