version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - demo1
      - demo2
      - demo3
    networks:
      - web

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - "5432:5432"

  demo1:
    image: nginx:alpine
    container_name: demo1
    restart: unless-stopped
    volumes:
      - ./demo1:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - web
      - backend

  demo2:
    image: nginx:alpine
    container_name: demo2
    restart: unless-stopped
    volumes:
      - ./demo2:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - web
      - backend

  demo3:
    image: nginx:alpine
    container_name: demo3
    restart: unless-stopped
    volumes:
      - ./demo3:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - web
      - backend

networks:
  web:
    external: false
  backend:
    external: false

volumes:
  postgres_data:
  nginx_logs: